### ISSUE TITLE
"Error! No Taglists were found." (There ARE taglists)  

### ISSUE THREAD

**Issue by catkraze3** [RoseLaLuna/Prodosia#27]
I have two taglists set up, but the bot doesn't seem to think they exist.  My taglists are "Default" and "Members"

Here are their details:
Default:
- Abbreviation: Default
- Has Ratings: No
- Description:  The Default Taglist

Members:
- Abbreviation: Members
- Has Ratings: No
- Description:  For Members

I also have two Users added, myself and another.  We are both subscribed to both taglists.  I'll attach a screenshot of one of our user pages (with Imgur name and id edited out).  I'm not sure if this is right, but the only thing that changes when I subscribe or unsubscribe from a taglist is the presence of the "+" next to it's name on the left.  
![image](https://user-images.githubusercontent.com/10297676/40865632-4d429546-65c7-11e8-98d4-7b3d9067085e.png)

I have tried every possible variation of the tag, sub, and suball commands, but they each give an error:
tag example:  **prefix** tag **postid** Members
    Response:  Error! No taglists were found.
sub example:  **prefix** sub **ImgurName** Default
    Response:  Error! There was no subscription data detected.
suball example:  **prefix** suball **ImgurName**
    Response:  There were no "" quotation marks around the argument. Please check your syntax.

So, does anyone have any idea what I'm doing wrong?  I'd greatly appreciate any help!

**Comment by RoseLaLuna** [comment]
I have a strong suspicion this has to do with case-sensitivity. Could you please confirm this for me?

**Comment by catkraze3** [comment]
I did match the case on my comment to the case of the items in the bot program.  I also editing the taglist so that it was all lowercase and attempted it again with the same result.  On a different note, do I only to download the jar from https://github.com/RoseLaLuna/Prodosia/releases/tag/v1.0.1 or do I have to also download something else?

**Comment by RoseLaLuna** [comment]
Only the .jar is required. 

Thank you for your elaborate description. I can reproduce the bug, so I'll try to get it fixed asap.

**Comment by RoseLaLuna** [comment]
Here is a link to a hotfix for the issue. 
https://drive.google.com/open?id=1F27OYO2DCu_5Pp4B9QGDIf-d8tuRrjsI

When the other issues are properly resolved I'll bring it out as a full release.
